version: "3.8"

services:
  backend:
    build: ./backend
    container_name: devflow-backend
    ports:
      - "8000:8000"
    networks:
      - devflow-net

  frontend:
    build: ./frontend
    container_name: devflow-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - devflow-net

networks:
  devflow-net:
    driver: bridge
